# -*- coding: utf-8 -*-
"""
Created on Fri Apr 26 16:12:17 2024

@author: kuldeep.rana
"""

^INDIAVIX	INDIA VIX	NSI
^CNXAUTO	NIFTY AUTO	NSI
^CNXPSUBANK	NIFTY PSU BANK	NSI
NIFTYPVTBANK.NS	NIFTY PVT BANK	NSI
^CNXFMCG	NIFTY FMCG	NSI
^CNXMETAL	NIFTY METAL	NSI
^CNXPSE	NIFTY PSE	NSI
^CNX200	NIFTY 200	NSI
^CNXENERGY	NIFTY ENERGY	NSI
^CNXPHARMA	NIFTY PHARMA	NSI
^CNXMNC	NIFTY MNC	NSI
CPSE.NS	NIFTY CPSE	NSI
^CNXIT	NIFTY IT	NSI
^CNXINFRA	NIFTY INFRA	NSI
^CNXCONSUM	NIFTY CONSUMPTION	NSI
^CNXSERVICE	NIFTY SERV SECTOR	NSI
^CNXCMDT	NIFTY COMMODITIES	NSI
^CNXREALTY	NIFTY REALTY	NSI
^CNXMEDIA	NIFTY MEDIA	NSI
^CNXFIN	NIFTY FIN SERVICE	NSI
